### ISSUE TITLE
Some advice

### ISSUE THREAD

**Issue by ghost** [radar/elixir-irc#1]
I stumbled upon your project and read the README. If I can give you some advice:

> Should it be an OTP application?

Yes. Definitely. At some point you'll find yourself trying to re-implement OTP concepts, and it's going to be nasty.

> Was :ets the right choice?

For state storage, you either have ETS, or an Agent. ETS is useful for dumb key-value stuff, Agents can be more flexible. 

And you should [take a look](https://ircv3.net/) to IRCv3. At this point of development it'll be easier for you to implement the specs.
Happy new year BTW!

**Comment by radar** [comment]
Thanks very much for your advice! I appreciate it.

**Comment by ghost** [comment]
You're welcome ;-)
Tell me if you accept pull requests (or if you want to focus on some particular features)
